FROM osrf/ros:noetic-desktop

RUN apt update && \
    apt install -y \
    x11-apps \
    iputils-ping \
    git \
    gcc-10 \
    g++-10 \
    python3-catkin-tools \
    ros-noetic-libfranka \
    ros-noetic-franka-ros \
    ros-noetic-pinocchio \
    libeigen3-dev \
    libyaml-cpp-dev
 
# Build osqp from source.
RUN git clone -b v0.6.3 --recursive https://github.com/osqp/osqp.git osqp && \
    cd osqp && \
    git submodule foreach --recursive 'git config --global --add safe.directory . && git reset --hard' && \
    mkdir build && cd build && \
    cmake -G "Unix Makefiles" .. && \
    cmake --build . --target install && \
    cd ../.. && rm -rf osqp

# Update gcc compiler from 9 to 10.
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 1 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 1 && \
    echo source /opt/ros/noetic/setup.bash >> ~/.bashrc
    # echo 127.0.0.1 `hostname` >> /etc/hosts
