FROM osrf/ros:noetic-desktop

RUN apt update && \
    apt install -y \
    x11-apps \
    iputils-ping \
    git \
    libyaml-cpp-dev \
    libglfw3-dev \
    python3-catkin-tools

RUN echo source /opt/ros/noetic/setup.bash >> ~/.bashrc
    # echo 127.0.0.1 `hostname` >> /etc/hosts
